### ISSUE TITLE
temi stop my app

### ISSUE THREAD

**Issue by Lee827** [robotemi/sdk#15]
temi sometimes will stop my app and navigate to temi app home view, but not destroy my app.
I turn off stand by mode already.
I want to keep running my app, no stop.
What is the case that has this problem?

**Comment by ramisaban1** [comment]
Hello,

Thank you for reaching out to our developer support. My name is Rami and I work on temi's Software Engineering team. This could be due to a couple of reasons, but I would recommend you wait within the next 2 weeks, the next version will be released adding a new Kiosk mode. This mode has the ability to make your app the center app on temi thereby solving this issue. I have tested it myself and it seems to be working just fine.

If you are still looking for additional support, you feel free to reach out to us via developers@robotemi.com

Best,
Rami
