### ISSUE TITLE
Get Rid of the “Going to XYZ” Screen

### ISSUE THREAD

**Issue by lcarnevale** [robotemi/sdk#42]
Hello all,

I would like to get rid of the screen which is shown when Temi moves onto locations, thanks to this operation:

```kotlin
robot.goTo("myLocation")
```

Thus, my goal is making the robot moving while the screen is not shown up.

Best,
Lorenzo.

**Comment by ramisaban1** [comment]
Hello,

In order to remove the navigation screens, you would need to first classify your application as a kiosk application. Please refer to our documentation on Kiosk mode at https://github.com/robotemi/sdk/wiki/Kiosk-Mode.

Also in the documentation, we explain how to toggle the navigation billboard in order to hide the "Going to the LOCATION_NAME" screen. I believe you would need to call `toggleNavigationBillboard(true)` in order to hide the screen.
