### ISSUE TITLE
fetch map from ROBOX

### ISSUE THREAD

**Issue by uglyduck2019** [robotemi/sdk#63]
Hi,
as the release note version #118
"Adding API support for map fetch and goto coordinates"
Where I can find the API and relate document or code?
thanks

**Comment by Vorlif** [comment]
Hi all,

where can I find the release notes?

**Comment by PureSecDE** [comment]
Hi, everybody,

where can I find the release notes?

**Comment by chris-lsn** [comment]
Do you guys have any update about it?

**Comment by Thiago-LM** [comment]
It's strange 'cause since [this](https://github.com/robotemi/sdk/commit/f29c12dc03a56543f5dda82a977706c75595ccb7) commit, from Jan 20, that's already a map function, but only on branch [map2](https://github.com/robotemi/sdk/tree/map2) and [mapMerge](https://github.com/robotemi/sdk/tree/mapMerge). And I don't know how to use them on my Android Studio project.

**Comment by cyrsis** [comment]
it would be great to have this working.

So it is the indoor map so that I can just use it a reference for the indoor nav system?

**Comment by leslieam** [comment]
We are working on this. It will be ready in a few versions ahead.
